---
submission: false
type: oral   #oral, poster, table
lang: spanish
title: "Si te gusta la estadística, bancate los metámeros"
titlerunning: "Título"
authors:
   - firstname: Elio
     lastname: Campitelli
     email: "elio.campitelli@cima.fcen.uba.ar"
     country: Argentina
     affil: 1
     # webpage: "google.com"  # Optional 
     corresponding: true
     speaker: true
affiliations:
   - Centro de Investigaciones del Mar y la Atmósfera - CONICET
# authorrunning: P. Author et al.
# abstract: "ablablab"
keywords: 
   - "Mínimo"
   - "tres"
   - "palabras clave"
bibliography: latinRtest.bib
output: 
    latinr::latinr_article
keep_tex: false
params: 
  check_is_error: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.width = 4)
knitr::opts_knit$set(self.contained = FALSE)

# knitr::write_bib(c("base", "data.table", "ggplot2", "metR", "raster"), 
#                  file = "packages.bib")

hook_source = knitr::knit_hooks$get('source')
knitr::knit_hooks$set(source = function(x, options) {
   txt = hook_source(x, options)
   # extend the default source hook
   gsub('~', '\\\\mytilde', txt)
})

knitr::knit_theme$set("moe")
```


# Introducción

En 1973 Frank Anscombre creó cuatro sets de datos que compartían la media y el desvío de cada variable y su coeficiente de correlación pero que lucían muy distintos cuando se los grafica (ref). Desde entonces, el cuarteto de Anscombe se usa para ilustrar la importancia de visualizar los datos crudos en vez de confiar en los estadísticos. A pesar de eso, no existe mucha investigación sobre el fenómeno general de "datasets disintos con los mismos estadísticos" del cual el cuarteto de Anscombe es sólo un ejemplo. Además usar un conjunto de datos creados hace 50 años para enseñar esto da la impresión de que es un caso único o extraordinario. 

En este artículo propongo el nombre de "metámeros estadísticos" en analogía al concepto de colorimetría y presento el paquete metamer, que implementa el algoritmo de blabla (ref) para la creación automática de metámeros. 

# Fuente de metamerismo estadístico

El Demonio de Laplace no sabe ni necesita saber estadística. Él tiene puede conocer la posición y velocidad de cada partícula del universo y usar ese conocimiento para predecir su evolución. Pero los seres humanos no podemos analizar más de unos pocos números por vez. Si queremos entender el universo tenemos que resumir grandes cantidad de observaciones en unos pocos números. Necesitamos saber estadística.

La mayoría de los métodos estadísticos buscan reducir grandes cantidades de datos en unos pocos números interpretables y representativos. Esto implica que son funciones continuas (si dos datasets son similares, sus estadísticos deben ser similares) que pasan de un espacio de alta dimensión a uno de dimensión menor. No existen funciones con ambas propiedades que sean biyectivas\footnote{https://arxiv.org/pdf/1003.1467.pdf}, por lo que, para cualquier método estadístico, los mismos pocos números pueden ser producidos por una infinidad de sets de datos distintos. Por ejemplo, se necesitan $N$ momentos estadisticos para caracterizar unívocamente un set de datos de $N$ observaciones\footnote{Técnicamente unívocamente a menos a menos de una permutación.}. Como colorario, existen infinitos sets de datos de N observaciones que comparten los mismos $n < N$ momentos. 

\begin{definition}
Sea una función $E : A \rightarrow B$ y un $a_0 \in A$. El conjunto $M_{a, E}$ de todos los $a \in A$ tal que $E(a) = E(a_0)$ son los metámeros de $a_0$ con respecto a $E$. 
\end{definition}

Es decir, toda función no biyectiva tiene metámeros. El metamerismo es una consecuencia inevitable de los métodos estadísticos; no es un bug, es una característica. El Cuarteto de Anscombe es un ejemplo dramático, pero no debe entenderse como aplicable sólo a los momentos estadísticos. Tampoco debe concluirse que visualizar los datos sea la única solución, ya que al proyectar de los datos en un espacio bidimensional, la visualización también sufre de metamerismo. 

# Cómo crear metámeros

El paquete metamer implementa el algoritmo de (ref) para generar metámeros a partir de un dataset y una transformación estadística que debe preservarse. Al ser completamente genérico, permite ilustrar el metamerismo de cualquier transformación. Por ejemplo,.... 

